# ---
# kind: pipeline
# type: kubernetes
# name: Build Docker 


# ######################################################   trigger
# trigger:
#   branch:
#   - main
#   when:
#     event:
#       exclude:
#       - pull_request   


# ###################################################   build-push
# steps:
# - name: build-push
#   image: docker:dind
#   volumes:
#   - name: dockersock
#     path: /var/run  
#   privileged: true
#   commands:
#   - sleep 5 ## give docker enough time to start
#   #- docker login -u user_docker_hub -p password_docker_hub #ou qualquer registry
#   - docker build  -t siniqapoc/poc-site:${DRONE_COMMIT_SHA:0:7} .
#   #- docker push uzieljr/poc-site:${DRONE_COMMIT_SHA:0:7}


# ######################################################   Delivery
# # - name: delivery
# #   image: uzieljr/plugin-drone:5.0
# #   commands:
# #   - git clone git@github.com:uzieljr/deploy-applications.git
# #   - cd deploy-applications 
# #   - sed -E -i.bak 's%(uzieljr/poc-site:).*%uzieljr/poc-site:${DRONE_COMMIT_SHA:0:7}%' site-helm/templates/uzi-poc-site-deployment.yml
# #   - git add . && git commit -m "Change image site-poc to uzieljr/poc-site:${DRONE_COMMIT_SHA:0:7}" && git push


# ########################################################   Services   
# # Este é um serviçe do kubernetes que nos da a possibilidade de subir um container dentro de um nodepool do aks
# # Usando docker diretamente
# services:
# - name: docker
#   image: docker:dind
#   privileged: true
#   volumes:
#   - name: dockersock
#     path: /var/run
# volumes:
# - name: dockersock
#   temp: {}

# ---

# kind: pipeline
# type: kubernetes
# name: Build Java 


# ######################################################   trigger
# trigger:
#   branch:
#   - main
#   when:
#     event:
#       exclude:
#       - pull_request   


# ###################################################   build-push
# steps:
# - name: Buildando Aplicativo Java
#   image: maven:3.5.2-jdk-8-alpine
#   commands:
#   - cd simple-java-project && mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V


# ######################################################   Delivery
# # - name: delivery
# #   image: uzieljr/plugin-drone:5.0
# #   commands:
# #   - git clone git@github.com:uzieljr/deploy-applications.git
# #   - cd deploy-applications 
# #   - sed -E -i.bak 's%(uzieljr/poc-site:).*%uzieljr/poc-site:${DRONE_COMMIT_SHA:0:7}%' site-helm/templates/uzi-poc-site-deployment.yml
# #   - git add . && git commit -m "Change image site-poc to uzieljr/poc-site:${DRONE_COMMIT_SHA:0:7}" && git push


# ########################################################   Services   
# # Este é um serviçe do kubernetes que nos da a possibilidade de subir um container dentro de um nodepool do aks
# # Usando docker diretamente

---
kind: pipeline
type: kubernetes
name: Terraform Plan & Apply

trigger:
  branch:
  - main
  when:
    event:
      exclude:
      - pull_request   

steps:
- name: terraform-plan
  image: jmccann/drone-terraform:1
  settings:
    plan: true
    root_dir: .
    parallelism: 4
    sensitive: true
    vars:
      ARM_CLIENT_ID:
        from_secret: ARM_CLIENT_ID
      ARM_CLIENT_SECRET:
        from_secret: ARM_CLIENT_SECRET 
      ARM_SUBSCRIPTION_ID:
        from_secret: ARM_SUBSCRIPTION_ID
      ARM_TENANT_ID:
        from_secret: ARM_TENANT_ID

- name: terraform-apply
  image: jmccann/drone-terraform:1
  settings:
    plan: false
    root_dir: .
    parallelism: 4
    sensitive: true
    vars:
      ARM_CLIENT_ID:
        from_secret: ARM_CLIENT_ID
      ARM_CLIENT_SECRET:
        from_secret: ARM_CLIENT_SECRET 
      ARM_SUBSCRIPTION_ID:
        from_secret: ARM_SUBSCRIPTION_ID
      ARM_TENANT_ID:
        from_secret: ARM_TENANT_ID