---
kind: pipeline
type: kubernetes
name: Terraform Plan & Apply

trigger:
  branch:
  - main
  when:
    event:
      exclude:
      - pull_request   

steps:
- name: terraform-init
  image: hashicorp/terraform:1.5.7
  commands:
  - terraform init
  environment:
    ARM_CLIENT_ID:
      from_secret: ARM_CLIENT_ID
    ARM_CLIENT_SECRET:
      from_secret: ARM_CLIENT_SECRET 
    ARM_SUBSCRIPTION_ID:
      from_secret: ARM_SUBSCRIPTION_ID
    ARM_TENANT_ID:
      from_secret: ARM_TENANT_ID

- name: terraform-validate
  image: hashicorp/terraform:1.5.7
  commands:
  - terraform validate
  environment:
    ARM_CLIENT_ID:
      from_secret: ARM_CLIENT_ID
    ARM_CLIENT_SECRET:
      from_secret: ARM_CLIENT_SECRET 
    ARM_SUBSCRIPTION_ID:
      from_secret: ARM_SUBSCRIPTION_ID
    ARM_TENANT_ID:
      from_secret: ARM_TENANT_ID

- name: terraform-plan
  image: hashicorp/terraform:1.5.7
  commands:
  - terraform plan -out=tfplan
  environment:
    ARM_CLIENT_ID:
      from_secret: ARM_CLIENT_ID
    ARM_CLIENT_SECRET:
      from_secret: ARM_CLIENT_SECRET 
    ARM_SUBSCRIPTION_ID:
      from_secret: ARM_SUBSCRIPTION_ID
    ARM_TENANT_ID:
      from_secret: ARM_TENANT_ID

- name: terraform-apply
  image: hashicorp/terraform:1.5.7
  commands:
  - terraform apply -auto-approve tfplan
  environment:
    ARM_CLIENT_ID:
      from_secret: ARM_CLIENT_ID
    ARM_CLIENT_SECRET:
      from_secret: ARM_CLIENT_SECRET 
    ARM_SUBSCRIPTION_ID:
      from_secret: ARM_SUBSCRIPTION_ID
    ARM_TENANT_ID:
      from_secret: ARM_TENANT_ID
  when:
    branch:
    - main